package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Inventory generated by hbm2java
 */
public class Inventory implements java.io.Serializable {

	private InventoryId id;
	private Shop shop;
	private Supplierproductline supplierproductline;

	public Inventory() {
	}

	public Inventory(InventoryId id) {
		this.id = id;
	}

	public Inventory(InventoryId id, Shop shop,
			Supplierproductline supplierproductline) {
		this.id = id;
		this.shop = shop;
		this.supplierproductline = supplierproductline;
	}

	public InventoryId getId() {
		return this.id;
	}

	public void setId(InventoryId id) {
		this.id = id;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
