package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * LendId generated by hbm2java
 */
public class LendId implements java.io.Serializable {

	private Integer quantity;
	private String inventoryRemark;
	private String inventoryStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private int fromShop;
	private int toShop;
	private Integer supplierId;
	private Integer productId;

	public LendId() {
	}

	public LendId(String inventoryStatus, int fromShop, int toShop) {
		this.inventoryStatus = inventoryStatus;
		this.fromShop = fromShop;
		this.toShop = toShop;
	}

	public LendId(Integer quantity, String inventoryRemark,
			String inventoryStatus, Integer lastUpdateUser,
			Date lastUpdateDate, int fromShop, int toShop, Integer supplierId,
			Integer productId) {
		this.quantity = quantity;
		this.inventoryRemark = inventoryRemark;
		this.inventoryStatus = inventoryStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.fromShop = fromShop;
		this.toShop = toShop;
		this.supplierId = supplierId;
		this.productId = productId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getInventoryRemark() {
		return this.inventoryRemark;
	}

	public void setInventoryRemark(String inventoryRemark) {
		this.inventoryRemark = inventoryRemark;
	}

	public String getInventoryStatus() {
		return this.inventoryStatus;
	}

	public void setInventoryStatus(String inventoryStatus) {
		this.inventoryStatus = inventoryStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getFromShop() {
		return this.fromShop;
	}

	public void setFromShop(int fromShop) {
		this.fromShop = fromShop;
	}

	public int getToShop() {
		return this.toShop;
	}

	public void setToShop(int toShop) {
		this.toShop = toShop;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LendId))
			return false;
		LendId castOther = (LendId) other;

		return ((this.getQuantity() == castOther.getQuantity()) || (this
				.getQuantity() != null && castOther.getQuantity() != null && this
				.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getInventoryRemark() == castOther
						.getInventoryRemark()) || (this.getInventoryRemark() != null
						&& castOther.getInventoryRemark() != null && this
						.getInventoryRemark().equals(
								castOther.getInventoryRemark())))
				&& ((this.getInventoryStatus() == castOther
						.getInventoryStatus()) || (this.getInventoryStatus() != null
						&& castOther.getInventoryStatus() != null && this
						.getInventoryStatus().equals(
								castOther.getInventoryStatus())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser()) || (this
						.getLastUpdateUser() != null
						&& castOther.getLastUpdateUser() != null && this
						.getLastUpdateUser().equals(
								castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate()) || (this
						.getLastUpdateDate() != null
						&& castOther.getLastUpdateDate() != null && this
						.getLastUpdateDate().equals(
								castOther.getLastUpdateDate())))
				&& (this.getFromShop() == castOther.getFromShop())
				&& (this.getToShop() == castOther.getToShop())
				&& ((this.getSupplierId() == castOther.getSupplierId()) || (this
						.getSupplierId() != null
						&& castOther.getSupplierId() != null && this
						.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37
				* result
				+ (getInventoryRemark() == null ? 0 : this.getInventoryRemark()
						.hashCode());
		result = 37
				* result
				+ (getInventoryStatus() == null ? 0 : this.getInventoryStatus()
						.hashCode());
		result = 37
				* result
				+ (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser()
						.hashCode());
		result = 37
				* result
				+ (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate()
						.hashCode());
		result = 37 * result + this.getFromShop();
		result = 37 * result + this.getToShop();
		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
