package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Logisticsorderline generated by hbm2java
 */
public class Logisticsorderline implements java.io.Serializable {

	private LogisticsorderlineId id;
	private Logisticsorder logisticsorder;
	private Supplierproductline supplierproductline;

	public Logisticsorderline() {
	}

	public Logisticsorderline(LogisticsorderlineId id) {
		this.id = id;
	}

	public Logisticsorderline(LogisticsorderlineId id,
			Logisticsorder logisticsorder,
			Supplierproductline supplierproductline) {
		this.id = id;
		this.logisticsorder = logisticsorder;
		this.supplierproductline = supplierproductline;
	}

	public LogisticsorderlineId getId() {
		return this.id;
	}

	public void setId(LogisticsorderlineId id) {
		this.id = id;
	}

	public Logisticsorder getLogisticsorder() {
		return this.logisticsorder;
	}

	public void setLogisticsorder(Logisticsorder logisticsorder) {
		this.logisticsorder = logisticsorder;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
