package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Logisticsorder generated by hbm2java
 */
public class Logisticsorder implements java.io.Serializable {

	private int logisticsOrderId;
	private Shop shop;
	private Date logisticsOrderReceiveDate;
	private String logisticsOrderRemark;
	private String logisticsOrderStatus;
	private int lastUpdateUser;
	private Date lastUpdateDate;
	private Integer logisticsOrderPrice;
	private Integer logisticsOrderTip;
	private Set<Logisticsorderline> logisticsorderlines = new HashSet<Logisticsorderline>(
			0);

	public Logisticsorder() {
	}

	public Logisticsorder(int logisticsOrderId, String logisticsOrderStatus,
			int lastUpdateUser, Date lastUpdateDate) {
		this.logisticsOrderId = logisticsOrderId;
		this.logisticsOrderStatus = logisticsOrderStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
	}

	public Logisticsorder(int logisticsOrderId, Shop shop,
			Date logisticsOrderReceiveDate, String logisticsOrderRemark,
			String logisticsOrderStatus, int lastUpdateUser,
			Date lastUpdateDate, Integer logisticsOrderPrice,
			Integer logisticsOrderTip,
			Set<Logisticsorderline> logisticsorderlines) {
		this.logisticsOrderId = logisticsOrderId;
		this.shop = shop;
		this.logisticsOrderReceiveDate = logisticsOrderReceiveDate;
		this.logisticsOrderRemark = logisticsOrderRemark;
		this.logisticsOrderStatus = logisticsOrderStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.logisticsOrderPrice = logisticsOrderPrice;
		this.logisticsOrderTip = logisticsOrderTip;
		this.logisticsorderlines = logisticsorderlines;
	}

	public int getLogisticsOrderId() {
		return this.logisticsOrderId;
	}

	public void setLogisticsOrderId(int logisticsOrderId) {
		this.logisticsOrderId = logisticsOrderId;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Date getLogisticsOrderReceiveDate() {
		return this.logisticsOrderReceiveDate;
	}

	public void setLogisticsOrderReceiveDate(Date logisticsOrderReceiveDate) {
		this.logisticsOrderReceiveDate = logisticsOrderReceiveDate;
	}

	public String getLogisticsOrderRemark() {
		return this.logisticsOrderRemark;
	}

	public void setLogisticsOrderRemark(String logisticsOrderRemark) {
		this.logisticsOrderRemark = logisticsOrderRemark;
	}

	public String getLogisticsOrderStatus() {
		return this.logisticsOrderStatus;
	}

	public void setLogisticsOrderStatus(String logisticsOrderStatus) {
		this.logisticsOrderStatus = logisticsOrderStatus;
	}

	public int getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(int lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getLogisticsOrderPrice() {
		return this.logisticsOrderPrice;
	}

	public void setLogisticsOrderPrice(Integer logisticsOrderPrice) {
		this.logisticsOrderPrice = logisticsOrderPrice;
	}

	public Integer getLogisticsOrderTip() {
		return this.logisticsOrderTip;
	}

	public void setLogisticsOrderTip(Integer logisticsOrderTip) {
		this.logisticsOrderTip = logisticsOrderTip;
	}

	public Set<Logisticsorderline> getLogisticsorderlines() {
		return this.logisticsorderlines;
	}

	public void setLogisticsorderlines(
			Set<Logisticsorderline> logisticsorderlines) {
		this.logisticsorderlines = logisticsorderlines;
	}

}
