package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Lost generated by hbm2java
 */
public class Lost implements java.io.Serializable {

	private LostId id;
	private Shop shop;
	private Supplierproductline supplierproductline;

	public Lost() {
	}

	public Lost(LostId id) {
		this.id = id;
	}

	public Lost(LostId id, Shop shop, Supplierproductline supplierproductline) {
		this.id = id;
		this.shop = shop;
		this.supplierproductline = supplierproductline;
	}

	public LostId getId() {
		return this.id;
	}

	public void setId(LostId id) {
		this.id = id;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
