package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Mobileproduct generated by hbm2java
 */
public class Mobileproduct implements java.io.Serializable {

	private int mobileProductId;
	private Productcompany productcompany;
	private String mobileProductName;
	private String mobileProductStortName;
	private String mobileProductModel;
	private String mobileProductStatus;
	private String lastUpdateUser;
	private Date lastUpdateDate;

	public Mobileproduct() {
	}

	public Mobileproduct(int mobileProductId, String mobileProductName) {
		this.mobileProductId = mobileProductId;
		this.mobileProductName = mobileProductName;
	}

	public Mobileproduct(int mobileProductId, Productcompany productcompany,
			String mobileProductName, String mobileProductStortName,
			String mobileProductModel, String mobileProductStatus,
			String lastUpdateUser, Date lastUpdateDate) {
		this.mobileProductId = mobileProductId;
		this.productcompany = productcompany;
		this.mobileProductName = mobileProductName;
		this.mobileProductStortName = mobileProductStortName;
		this.mobileProductModel = mobileProductModel;
		this.mobileProductStatus = mobileProductStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getMobileProductId() {
		return this.mobileProductId;
	}

	public void setMobileProductId(int mobileProductId) {
		this.mobileProductId = mobileProductId;
	}

	public Productcompany getProductcompany() {
		return this.productcompany;
	}

	public void setProductcompany(Productcompany productcompany) {
		this.productcompany = productcompany;
	}

	public String getMobileProductName() {
		return this.mobileProductName;
	}

	public void setMobileProductName(String mobileProductName) {
		this.mobileProductName = mobileProductName;
	}

	public String getMobileProductStortName() {
		return this.mobileProductStortName;
	}

	public void setMobileProductStortName(String mobileProductStortName) {
		this.mobileProductStortName = mobileProductStortName;
	}

	public String getMobileProductModel() {
		return this.mobileProductModel;
	}

	public void setMobileProductModel(String mobileProductModel) {
		this.mobileProductModel = mobileProductModel;
	}

	public String getMobileProductStatus() {
		return this.mobileProductStatus;
	}

	public void setMobileProductStatus(String mobileProductStatus) {
		this.mobileProductStatus = mobileProductStatus;
	}

	public String getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(String lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
