package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Mobilecovertype generated by hbm2java
 */
public class Mobilecovertype implements java.io.Serializable {

	private int mobileCoverTypeId;
	private String mobileCoverTypeName;
	private String mobileCoverTypeStortName;
	private String mobileCoverTypeStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;

	public Mobilecovertype() {
	}

	public Mobilecovertype(int mobileCoverTypeId, String mobileCoverTypeName,
			String mobileCoverTypeStatus) {
		this.mobileCoverTypeId = mobileCoverTypeId;
		this.mobileCoverTypeName = mobileCoverTypeName;
		this.mobileCoverTypeStatus = mobileCoverTypeStatus;
	}

	public Mobilecovertype(int mobileCoverTypeId, String mobileCoverTypeName,
			String mobileCoverTypeStortName, String mobileCoverTypeStatus,
			Integer lastUpdateUser, Date lastUpdateDate) {
		this.mobileCoverTypeId = mobileCoverTypeId;
		this.mobileCoverTypeName = mobileCoverTypeName;
		this.mobileCoverTypeStortName = mobileCoverTypeStortName;
		this.mobileCoverTypeStatus = mobileCoverTypeStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getMobileCoverTypeId() {
		return this.mobileCoverTypeId;
	}

	public void setMobileCoverTypeId(int mobileCoverTypeId) {
		this.mobileCoverTypeId = mobileCoverTypeId;
	}

	public String getMobileCoverTypeName() {
		return this.mobileCoverTypeName;
	}

	public void setMobileCoverTypeName(String mobileCoverTypeName) {
		this.mobileCoverTypeName = mobileCoverTypeName;
	}

	public String getMobileCoverTypeStortName() {
		return this.mobileCoverTypeStortName;
	}

	public void setMobileCoverTypeStortName(String mobileCoverTypeStortName) {
		this.mobileCoverTypeStortName = mobileCoverTypeStortName;
	}

	public String getMobileCoverTypeStatus() {
		return this.mobileCoverTypeStatus;
	}

	public void setMobileCoverTypeStatus(String mobileCoverTypeStatus) {
		this.mobileCoverTypeStatus = mobileCoverTypeStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
