package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private int productId;
	private Productcompany productcompany;
	private Producttype producttype;
	private String productName;
	private String productCode;
	private String productRemark;
	private Integer lastSupplierPrice;
	private Integer productPrice;
	private String productStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Set<Supplierproductline> supplierproductlines = new HashSet<Supplierproductline>(
			0);

	public Product() {
	}

	public Product(int productId, String productName, String productStatus) {
		this.productId = productId;
		this.productName = productName;
		this.productStatus = productStatus;
	}

	public Product(int productId, Productcompany productcompany,
			Producttype producttype, String productName, String productCode,
			String productRemark, Integer lastSupplierPrice,
			Integer productPrice, String productStatus, Integer lastUpdateUser,
			Date lastUpdateDate, Set<Supplierproductline> supplierproductlines) {
		this.productId = productId;
		this.productcompany = productcompany;
		this.producttype = producttype;
		this.productName = productName;
		this.productCode = productCode;
		this.productRemark = productRemark;
		this.lastSupplierPrice = lastSupplierPrice;
		this.productPrice = productPrice;
		this.productStatus = productStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.supplierproductlines = supplierproductlines;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Productcompany getProductcompany() {
		return this.productcompany;
	}

	public void setProductcompany(Productcompany productcompany) {
		this.productcompany = productcompany;
	}

	public Producttype getProducttype() {
		return this.producttype;
	}

	public void setProducttype(Producttype producttype) {
		this.producttype = producttype;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public String getProductRemark() {
		return this.productRemark;
	}

	public void setProductRemark(String productRemark) {
		this.productRemark = productRemark;
	}

	public Integer getLastSupplierPrice() {
		return this.lastSupplierPrice;
	}

	public void setLastSupplierPrice(Integer lastSupplierPrice) {
		this.lastSupplierPrice = lastSupplierPrice;
	}

	public Integer getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(Integer productPrice) {
		this.productPrice = productPrice;
	}

	public String getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(String productStatus) {
		this.productStatus = productStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set<Supplierproductline> getSupplierproductlines() {
		return this.supplierproductlines;
	}

	public void setSupplierproductlines(
			Set<Supplierproductline> supplierproductlines) {
		this.supplierproductlines = supplierproductlines;
	}

}
