package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producttype generated by hbm2java
 */
public class Producttype implements java.io.Serializable {

	private int productTypeId;
	private String productTypeName;
	private String productTypeStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Set<Product> products = new HashSet<Product>(0);

	public Producttype() {
	}

	public Producttype(int productTypeId, String productTypeName) {
		this.productTypeId = productTypeId;
		this.productTypeName = productTypeName;
	}

	public Producttype(int productTypeId, String productTypeName,
			String productTypeStatus, Integer lastUpdateUser,
			Date lastUpdateDate, Set<Product> products) {
		this.productTypeId = productTypeId;
		this.productTypeName = productTypeName;
		this.productTypeStatus = productTypeStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.products = products;
	}

	public int getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(int productTypeId) {
		this.productTypeId = productTypeId;
	}

	public String getProductTypeName() {
		return this.productTypeName;
	}

	public void setProductTypeName(String productTypeName) {
		this.productTypeName = productTypeName;
	}

	public String getProductTypeStatus() {
		return this.productTypeStatus;
	}

	public void setProductTypeStatus(String productTypeStatus) {
		this.productTypeStatus = productTypeStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
