package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Productcolor generated by hbm2java
 */
public class Productcolor implements java.io.Serializable {

	private int productColorId;
	private String productColorName;
	private String productColorStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;

	public Productcolor() {
	}

	public Productcolor(int productColorId, String productColorName,
			String productColorStatus) {
		this.productColorId = productColorId;
		this.productColorName = productColorName;
		this.productColorStatus = productColorStatus;
	}

	public Productcolor(int productColorId, String productColorName,
			String productColorStatus, Integer lastUpdateUser,
			Date lastUpdateDate) {
		this.productColorId = productColorId;
		this.productColorName = productColorName;
		this.productColorStatus = productColorStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
	}

	public int getProductColorId() {
		return this.productColorId;
	}

	public void setProductColorId(int productColorId) {
		this.productColorId = productColorId;
	}

	public String getProductColorName() {
		return this.productColorName;
	}

	public void setProductColorName(String productColorName) {
		this.productColorName = productColorName;
	}

	public String getProductColorStatus() {
		return this.productColorStatus;
	}

	public void setProductColorStatus(String productColorStatus) {
		this.productColorStatus = productColorStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

}
