package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SalesId generated by hbm2java
 */
public class SalesId implements java.io.Serializable {

	private Integer quantity;
	private String salesRemark;
	private String salesStatus;
	private Integer salesUser;
	private Date salesDate;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Integer shopId;
	private Integer supplierId;
	private Integer productId;

	public SalesId() {
	}

	public SalesId(String salesStatus) {
		this.salesStatus = salesStatus;
	}

	public SalesId(Integer quantity, String salesRemark, String salesStatus,
			Integer salesUser, Date salesDate, Integer lastUpdateUser,
			Date lastUpdateDate, Integer shopId, Integer supplierId,
			Integer productId) {
		this.quantity = quantity;
		this.salesRemark = salesRemark;
		this.salesStatus = salesStatus;
		this.salesUser = salesUser;
		this.salesDate = salesDate;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.shopId = shopId;
		this.supplierId = supplierId;
		this.productId = productId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getSalesRemark() {
		return this.salesRemark;
	}

	public void setSalesRemark(String salesRemark) {
		this.salesRemark = salesRemark;
	}

	public String getSalesStatus() {
		return this.salesStatus;
	}

	public void setSalesStatus(String salesStatus) {
		this.salesStatus = salesStatus;
	}

	public Integer getSalesUser() {
		return this.salesUser;
	}

	public void setSalesUser(Integer salesUser) {
		this.salesUser = salesUser;
	}

	public Date getSalesDate() {
		return this.salesDate;
	}

	public void setSalesDate(Date salesDate) {
		this.salesDate = salesDate;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getShopId() {
		return this.shopId;
	}

	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesId))
			return false;
		SalesId castOther = (SalesId) other;

		return ((this.getQuantity() == castOther.getQuantity()) || (this
				.getQuantity() != null && castOther.getQuantity() != null && this
				.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getSalesRemark() == castOther.getSalesRemark()) || (this
						.getSalesRemark() != null
						&& castOther.getSalesRemark() != null && this
						.getSalesRemark().equals(castOther.getSalesRemark())))
				&& ((this.getSalesStatus() == castOther.getSalesStatus()) || (this
						.getSalesStatus() != null
						&& castOther.getSalesStatus() != null && this
						.getSalesStatus().equals(castOther.getSalesStatus())))
				&& ((this.getSalesUser() == castOther.getSalesUser()) || (this
						.getSalesUser() != null
						&& castOther.getSalesUser() != null && this
						.getSalesUser().equals(castOther.getSalesUser())))
				&& ((this.getSalesDate() == castOther.getSalesDate()) || (this
						.getSalesDate() != null
						&& castOther.getSalesDate() != null && this
						.getSalesDate().equals(castOther.getSalesDate())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser()) || (this
						.getLastUpdateUser() != null
						&& castOther.getLastUpdateUser() != null && this
						.getLastUpdateUser().equals(
								castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate()) || (this
						.getLastUpdateDate() != null
						&& castOther.getLastUpdateDate() != null && this
						.getLastUpdateDate().equals(
								castOther.getLastUpdateDate())))
				&& ((this.getShopId() == castOther.getShopId()) || (this
						.getShopId() != null && castOther.getShopId() != null && this
						.getShopId().equals(castOther.getShopId())))
				&& ((this.getSupplierId() == castOther.getSupplierId()) || (this
						.getSupplierId() != null
						&& castOther.getSupplierId() != null && this
						.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37
				* result
				+ (getSalesRemark() == null ? 0 : this.getSalesRemark()
						.hashCode());
		result = 37
				* result
				+ (getSalesStatus() == null ? 0 : this.getSalesStatus()
						.hashCode());
		result = 37 * result
				+ (getSalesUser() == null ? 0 : this.getSalesUser().hashCode());
		result = 37 * result
				+ (getSalesDate() == null ? 0 : this.getSalesDate().hashCode());
		result = 37
				* result
				+ (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser()
						.hashCode());
		result = 37
				* result
				+ (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate()
						.hashCode());
		result = 37 * result
				+ (getShopId() == null ? 0 : this.getShopId().hashCode());
		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
