package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Sales generated by hbm2java
 */
public class Sales implements java.io.Serializable {

	private SalesId id;
	private Shop shop;
	private Supplierproductline supplierproductline;

	public Sales() {
	}

	public Sales(SalesId id) {
		this.id = id;
	}

	public Sales(SalesId id, Shop shop, Supplierproductline supplierproductline) {
		this.id = id;
		this.shop = shop;
		this.supplierproductline = supplierproductline;
	}

	public SalesId getId() {
		return this.id;
	}

	public void setId(SalesId id) {
		this.id = id;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
