package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop implements java.io.Serializable {

	private int shopId;
	private int shopName;
	private String shopType;
	private String shopRemark;
	private String shopStatus;
	private Set<Lost> losts = new HashSet<Lost>(0);
	private Set<Supplierorder> supplierorders = new HashSet<Supplierorder>(0);
	private Set<Supplierpreorder> supplierpreorders = new HashSet<Supplierpreorder>(
			0);
	private Set<Logisticsorder> logisticsorders = new HashSet<Logisticsorder>(0);
	private Set<Sales> saleses = new HashSet<Sales>(0);
	private Set<Inventory> inventories = new HashSet<Inventory>(0);

	public Shop() {
	}

	public Shop(int shopId, int shopName, String shopType, String shopStatus) {
		this.shopId = shopId;
		this.shopName = shopName;
		this.shopType = shopType;
		this.shopStatus = shopStatus;
	}

	public Shop(int shopId, int shopName, String shopType, String shopRemark,
			String shopStatus, Set<Lost> losts,
			Set<Supplierorder> supplierorders,
			Set<Supplierpreorder> supplierpreorders,
			Set<Logisticsorder> logisticsorders, Set<Sales> saleses,
			Set<Inventory> inventories) {
		this.shopId = shopId;
		this.shopName = shopName;
		this.shopType = shopType;
		this.shopRemark = shopRemark;
		this.shopStatus = shopStatus;
		this.losts = losts;
		this.supplierorders = supplierorders;
		this.supplierpreorders = supplierpreorders;
		this.logisticsorders = logisticsorders;
		this.saleses = saleses;
		this.inventories = inventories;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public int getShopName() {
		return this.shopName;
	}

	public void setShopName(int shopName) {
		this.shopName = shopName;
	}

	public String getShopType() {
		return this.shopType;
	}

	public void setShopType(String shopType) {
		this.shopType = shopType;
	}

	public String getShopRemark() {
		return this.shopRemark;
	}

	public void setShopRemark(String shopRemark) {
		this.shopRemark = shopRemark;
	}

	public String getShopStatus() {
		return this.shopStatus;
	}

	public void setShopStatus(String shopStatus) {
		this.shopStatus = shopStatus;
	}

	public Set<Lost> getLosts() {
		return this.losts;
	}

	public void setLosts(Set<Lost> losts) {
		this.losts = losts;
	}

	public Set<Supplierorder> getSupplierorders() {
		return this.supplierorders;
	}

	public void setSupplierorders(Set<Supplierorder> supplierorders) {
		this.supplierorders = supplierorders;
	}

	public Set<Supplierpreorder> getSupplierpreorders() {
		return this.supplierpreorders;
	}

	public void setSupplierpreorders(Set<Supplierpreorder> supplierpreorders) {
		this.supplierpreorders = supplierpreorders;
	}

	public Set<Logisticsorder> getLogisticsorders() {
		return this.logisticsorders;
	}

	public void setLogisticsorders(Set<Logisticsorder> logisticsorders) {
		this.logisticsorders = logisticsorders;
	}

	public Set<Sales> getSaleses() {
		return this.saleses;
	}

	public void setSaleses(Set<Sales> saleses) {
		this.saleses = saleses;
	}

	public Set<Inventory> getInventories() {
		return this.inventories;
	}

	public void setInventories(Set<Inventory> inventories) {
		this.inventories = inventories;
	}

}
