package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Supplierpreorderline generated by hbm2java
 */
public class Supplierpreorderline implements java.io.Serializable {

	private SupplierpreorderlineId id;
	private Supplierpreorder supplierpreorder;
	private Supplierproductline supplierproductline;

	public Supplierpreorderline() {
	}

	public Supplierpreorderline(SupplierpreorderlineId id) {
		this.id = id;
	}

	public Supplierpreorderline(SupplierpreorderlineId id,
			Supplierpreorder supplierpreorder,
			Supplierproductline supplierproductline) {
		this.id = id;
		this.supplierpreorder = supplierpreorder;
		this.supplierproductline = supplierproductline;
	}

	public SupplierpreorderlineId getId() {
		return this.id;
	}

	public void setId(SupplierpreorderlineId id) {
		this.id = id;
	}

	public Supplierpreorder getSupplierpreorder() {
		return this.supplierpreorder;
	}

	public void setSupplierpreorder(Supplierpreorder supplierpreorder) {
		this.supplierpreorder = supplierpreorder;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
