package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * SupplierproductlineId generated by hbm2java
 */
public class SupplierproductlineId implements java.io.Serializable {

	private int supplierId;
	private int productId;

	public SupplierproductlineId() {
	}

	public SupplierproductlineId(int supplierId, int productId) {
		this.supplierId = supplierId;
		this.productId = productId;
	}

	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupplierproductlineId))
			return false;
		SupplierproductlineId castOther = (SupplierproductlineId) other;

		return (this.getSupplierId() == castOther.getSupplierId())
				&& (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSupplierId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
