package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supplierpreorder generated by hbm2java
 */
public class Supplierpreorder implements java.io.Serializable {

	private int preOrderId;
	private Shop shop;
	private Integer appraiseHkdtotalPrice;
	private String oreOrderRemark;
	private String preOrderStatus;
	private int lastUpdateUser;
	private Date lastUpdateDate;
	private Set<Supplierpreorderline> supplierpreorderlines = new HashSet<Supplierpreorderline>(
			0);

	public Supplierpreorder() {
	}

	public Supplierpreorder(int preOrderId, String preOrderStatus,
			int lastUpdateUser, Date lastUpdateDate) {
		this.preOrderId = preOrderId;
		this.preOrderStatus = preOrderStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
	}

	public Supplierpreorder(int preOrderId, Shop shop,
			Integer appraiseHkdtotalPrice, String oreOrderRemark,
			String preOrderStatus, int lastUpdateUser, Date lastUpdateDate,
			Set<Supplierpreorderline> supplierpreorderlines) {
		this.preOrderId = preOrderId;
		this.shop = shop;
		this.appraiseHkdtotalPrice = appraiseHkdtotalPrice;
		this.oreOrderRemark = oreOrderRemark;
		this.preOrderStatus = preOrderStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.supplierpreorderlines = supplierpreorderlines;
	}

	public int getPreOrderId() {
		return this.preOrderId;
	}

	public void setPreOrderId(int preOrderId) {
		this.preOrderId = preOrderId;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Integer getAppraiseHkdtotalPrice() {
		return this.appraiseHkdtotalPrice;
	}

	public void setAppraiseHkdtotalPrice(Integer appraiseHkdtotalPrice) {
		this.appraiseHkdtotalPrice = appraiseHkdtotalPrice;
	}

	public String getOreOrderRemark() {
		return this.oreOrderRemark;
	}

	public void setOreOrderRemark(String oreOrderRemark) {
		this.oreOrderRemark = oreOrderRemark;
	}

	public String getPreOrderStatus() {
		return this.preOrderStatus;
	}

	public void setPreOrderStatus(String preOrderStatus) {
		this.preOrderStatus = preOrderStatus;
	}

	public int getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(int lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set<Supplierpreorderline> getSupplierpreorderlines() {
		return this.supplierpreorderlines;
	}

	public void setSupplierpreorderlines(
			Set<Supplierpreorderline> supplierpreorderlines) {
		this.supplierpreorderlines = supplierpreorderlines;
	}

}
