package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SupplierorderlineId generated by hbm2java
 */
public class SupplierorderlineId implements java.io.Serializable {

	private Integer quantity;
	private Integer appraiseHkdprice;
	private Integer rmbprice;
	private Integer hkdprice;
	private String orderProductStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Integer orderId;
	private Integer supplierId;
	private Integer productId;

	public SupplierorderlineId() {
	}

	public SupplierorderlineId(String orderProductStatus) {
		this.orderProductStatus = orderProductStatus;
	}

	public SupplierorderlineId(Integer quantity, Integer appraiseHkdprice,
			Integer rmbprice, Integer hkdprice, String orderProductStatus,
			Integer lastUpdateUser, Date lastUpdateDate, Integer orderId,
			Integer supplierId, Integer productId) {
		this.quantity = quantity;
		this.appraiseHkdprice = appraiseHkdprice;
		this.rmbprice = rmbprice;
		this.hkdprice = hkdprice;
		this.orderProductStatus = orderProductStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.orderId = orderId;
		this.supplierId = supplierId;
		this.productId = productId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getAppraiseHkdprice() {
		return this.appraiseHkdprice;
	}

	public void setAppraiseHkdprice(Integer appraiseHkdprice) {
		this.appraiseHkdprice = appraiseHkdprice;
	}

	public Integer getRmbprice() {
		return this.rmbprice;
	}

	public void setRmbprice(Integer rmbprice) {
		this.rmbprice = rmbprice;
	}

	public Integer getHkdprice() {
		return this.hkdprice;
	}

	public void setHkdprice(Integer hkdprice) {
		this.hkdprice = hkdprice;
	}

	public String getOrderProductStatus() {
		return this.orderProductStatus;
	}

	public void setOrderProductStatus(String orderProductStatus) {
		this.orderProductStatus = orderProductStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupplierorderlineId))
			return false;
		SupplierorderlineId castOther = (SupplierorderlineId) other;

		return ((this.getQuantity() == castOther.getQuantity()) || (this
				.getQuantity() != null && castOther.getQuantity() != null && this
				.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getAppraiseHkdprice() == castOther
						.getAppraiseHkdprice()) || (this.getAppraiseHkdprice() != null
						&& castOther.getAppraiseHkdprice() != null && this
						.getAppraiseHkdprice().equals(
								castOther.getAppraiseHkdprice())))
				&& ((this.getRmbprice() == castOther.getRmbprice()) || (this
						.getRmbprice() != null
						&& castOther.getRmbprice() != null && this
						.getRmbprice().equals(castOther.getRmbprice())))
				&& ((this.getHkdprice() == castOther.getHkdprice()) || (this
						.getHkdprice() != null
						&& castOther.getHkdprice() != null && this
						.getHkdprice().equals(castOther.getHkdprice())))
				&& ((this.getOrderProductStatus() == castOther
						.getOrderProductStatus()) || (this
						.getOrderProductStatus() != null
						&& castOther.getOrderProductStatus() != null && this
						.getOrderProductStatus().equals(
								castOther.getOrderProductStatus())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser()) || (this
						.getLastUpdateUser() != null
						&& castOther.getLastUpdateUser() != null && this
						.getLastUpdateUser().equals(
								castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate()) || (this
						.getLastUpdateDate() != null
						&& castOther.getLastUpdateDate() != null && this
						.getLastUpdateDate().equals(
								castOther.getLastUpdateDate())))
				&& ((this.getOrderId() == castOther.getOrderId()) || (this
						.getOrderId() != null && castOther.getOrderId() != null && this
						.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getSupplierId() == castOther.getSupplierId()) || (this
						.getSupplierId() != null
						&& castOther.getSupplierId() != null && this
						.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37
				* result
				+ (getAppraiseHkdprice() == null ? 0 : this
						.getAppraiseHkdprice().hashCode());
		result = 37 * result
				+ (getRmbprice() == null ? 0 : this.getRmbprice().hashCode());
		result = 37 * result
				+ (getHkdprice() == null ? 0 : this.getHkdprice().hashCode());
		result = 37
				* result
				+ (getOrderProductStatus() == null ? 0 : this
						.getOrderProductStatus().hashCode());
		result = 37
				* result
				+ (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser()
						.hashCode());
		result = 37
				* result
				+ (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate()
						.hashCode());
		result = 37 * result
				+ (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
