package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {

	private int supplierId;
	private String supplierName;
	private String contactPerson;
	private String supplierPhone;
	private String supplierAddress;
	private String supplierFax;
	private String supplierEmail;
	private String supplierWeChat;
	private String supplierQq;
	private String supplierMsn;
	private String supplierAccount;
	private String supplierWebsite;
	private String supplierType;
	private String supplierRemark;
	private String supplierStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Set<Supplierproductline> supplierproductlines = new HashSet<Supplierproductline>(
			0);

	public Supplier() {
	}

	public Supplier(int supplierId, String supplierName, String supplierStatus) {
		this.supplierId = supplierId;
		this.supplierName = supplierName;
		this.supplierStatus = supplierStatus;
	}

	public Supplier(int supplierId, String supplierName, String contactPerson,
			String supplierPhone, String supplierAddress, String supplierFax,
			String supplierEmail, String supplierWeChat, String supplierQq,
			String supplierMsn, String supplierAccount, String supplierWebsite,
			String supplierType, String supplierRemark, String supplierStatus,
			Integer lastUpdateUser, Date lastUpdateDate,
			Set<Supplierproductline> supplierproductlines) {
		this.supplierId = supplierId;
		this.supplierName = supplierName;
		this.contactPerson = contactPerson;
		this.supplierPhone = supplierPhone;
		this.supplierAddress = supplierAddress;
		this.supplierFax = supplierFax;
		this.supplierEmail = supplierEmail;
		this.supplierWeChat = supplierWeChat;
		this.supplierQq = supplierQq;
		this.supplierMsn = supplierMsn;
		this.supplierAccount = supplierAccount;
		this.supplierWebsite = supplierWebsite;
		this.supplierType = supplierType;
		this.supplierRemark = supplierRemark;
		this.supplierStatus = supplierStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.supplierproductlines = supplierproductlines;
	}

	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	public String getSupplierPhone() {
		return this.supplierPhone;
	}

	public void setSupplierPhone(String supplierPhone) {
		this.supplierPhone = supplierPhone;
	}

	public String getSupplierAddress() {
		return this.supplierAddress;
	}

	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	public String getSupplierFax() {
		return this.supplierFax;
	}

	public void setSupplierFax(String supplierFax) {
		this.supplierFax = supplierFax;
	}

	public String getSupplierEmail() {
		return this.supplierEmail;
	}

	public void setSupplierEmail(String supplierEmail) {
		this.supplierEmail = supplierEmail;
	}

	public String getSupplierWeChat() {
		return this.supplierWeChat;
	}

	public void setSupplierWeChat(String supplierWeChat) {
		this.supplierWeChat = supplierWeChat;
	}

	public String getSupplierQq() {
		return this.supplierQq;
	}

	public void setSupplierQq(String supplierQq) {
		this.supplierQq = supplierQq;
	}

	public String getSupplierMsn() {
		return this.supplierMsn;
	}

	public void setSupplierMsn(String supplierMsn) {
		this.supplierMsn = supplierMsn;
	}

	public String getSupplierAccount() {
		return this.supplierAccount;
	}

	public void setSupplierAccount(String supplierAccount) {
		this.supplierAccount = supplierAccount;
	}

	public String getSupplierWebsite() {
		return this.supplierWebsite;
	}

	public void setSupplierWebsite(String supplierWebsite) {
		this.supplierWebsite = supplierWebsite;
	}

	public String getSupplierType() {
		return this.supplierType;
	}

	public void setSupplierType(String supplierType) {
		this.supplierType = supplierType;
	}

	public String getSupplierRemark() {
		return this.supplierRemark;
	}

	public void setSupplierRemark(String supplierRemark) {
		this.supplierRemark = supplierRemark;
	}

	public String getSupplierStatus() {
		return this.supplierStatus;
	}

	public void setSupplierStatus(String supplierStatus) {
		this.supplierStatus = supplierStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Set<Supplierproductline> getSupplierproductlines() {
		return this.supplierproductlines;
	}

	public void setSupplierproductlines(
			Set<Supplierproductline> supplierproductlines) {
		this.supplierproductlines = supplierproductlines;
	}

}
