package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * SupplierpreorderlineId generated by hbm2java
 */
public class SupplierpreorderlineId implements java.io.Serializable {

	private Integer quantity;
	private Integer appraiseHkdprice;
	private String preOrderProductStatus;
	private Integer lastUpdateUser;
	private Date lastUpdateDate;
	private Integer preOrderId;
	private Integer supplierId;
	private Integer productId;

	public SupplierpreorderlineId() {
	}

	public SupplierpreorderlineId(String preOrderProductStatus) {
		this.preOrderProductStatus = preOrderProductStatus;
	}

	public SupplierpreorderlineId(Integer quantity, Integer appraiseHkdprice,
			String preOrderProductStatus, Integer lastUpdateUser,
			Date lastUpdateDate, Integer preOrderId, Integer supplierId,
			Integer productId) {
		this.quantity = quantity;
		this.appraiseHkdprice = appraiseHkdprice;
		this.preOrderProductStatus = preOrderProductStatus;
		this.lastUpdateUser = lastUpdateUser;
		this.lastUpdateDate = lastUpdateDate;
		this.preOrderId = preOrderId;
		this.supplierId = supplierId;
		this.productId = productId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getAppraiseHkdprice() {
		return this.appraiseHkdprice;
	}

	public void setAppraiseHkdprice(Integer appraiseHkdprice) {
		this.appraiseHkdprice = appraiseHkdprice;
	}

	public String getPreOrderProductStatus() {
		return this.preOrderProductStatus;
	}

	public void setPreOrderProductStatus(String preOrderProductStatus) {
		this.preOrderProductStatus = preOrderProductStatus;
	}

	public Integer getLastUpdateUser() {
		return this.lastUpdateUser;
	}

	public void setLastUpdateUser(Integer lastUpdateUser) {
		this.lastUpdateUser = lastUpdateUser;
	}

	public Date getLastUpdateDate() {
		return this.lastUpdateDate;
	}

	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	public Integer getPreOrderId() {
		return this.preOrderId;
	}

	public void setPreOrderId(Integer preOrderId) {
		this.preOrderId = preOrderId;
	}

	public Integer getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupplierpreorderlineId))
			return false;
		SupplierpreorderlineId castOther = (SupplierpreorderlineId) other;

		return ((this.getQuantity() == castOther.getQuantity()) || (this
				.getQuantity() != null && castOther.getQuantity() != null && this
				.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getAppraiseHkdprice() == castOther
						.getAppraiseHkdprice()) || (this.getAppraiseHkdprice() != null
						&& castOther.getAppraiseHkdprice() != null && this
						.getAppraiseHkdprice().equals(
								castOther.getAppraiseHkdprice())))
				&& ((this.getPreOrderProductStatus() == castOther
						.getPreOrderProductStatus()) || (this
						.getPreOrderProductStatus() != null
						&& castOther.getPreOrderProductStatus() != null && this
						.getPreOrderProductStatus().equals(
								castOther.getPreOrderProductStatus())))
				&& ((this.getLastUpdateUser() == castOther.getLastUpdateUser()) || (this
						.getLastUpdateUser() != null
						&& castOther.getLastUpdateUser() != null && this
						.getLastUpdateUser().equals(
								castOther.getLastUpdateUser())))
				&& ((this.getLastUpdateDate() == castOther.getLastUpdateDate()) || (this
						.getLastUpdateDate() != null
						&& castOther.getLastUpdateDate() != null && this
						.getLastUpdateDate().equals(
								castOther.getLastUpdateDate())))
				&& ((this.getPreOrderId() == castOther.getPreOrderId()) || (this
						.getPreOrderId() != null
						&& castOther.getPreOrderId() != null && this
						.getPreOrderId().equals(castOther.getPreOrderId())))
				&& ((this.getSupplierId() == castOther.getSupplierId()) || (this
						.getSupplierId() != null
						&& castOther.getSupplierId() != null && this
						.getSupplierId().equals(castOther.getSupplierId())))
				&& ((this.getProductId() == castOther.getProductId()) || (this
						.getProductId() != null
						&& castOther.getProductId() != null && this
						.getProductId().equals(castOther.getProductId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37
				* result
				+ (getAppraiseHkdprice() == null ? 0 : this
						.getAppraiseHkdprice().hashCode());
		result = 37
				* result
				+ (getPreOrderProductStatus() == null ? 0 : this
						.getPreOrderProductStatus().hashCode());
		result = 37
				* result
				+ (getLastUpdateUser() == null ? 0 : this.getLastUpdateUser()
						.hashCode());
		result = 37
				* result
				+ (getLastUpdateDate() == null ? 0 : this.getLastUpdateDate()
						.hashCode());
		result = 37
				* result
				+ (getPreOrderId() == null ? 0 : this.getPreOrderId()
						.hashCode());
		result = 37
				* result
				+ (getSupplierId() == null ? 0 : this.getSupplierId()
						.hashCode());
		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		return result;
	}

}
