package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * Supplierorderline generated by hbm2java
 */
public class Supplierorderline implements java.io.Serializable {

	private SupplierorderlineId id;
	private Supplierorder supplierorder;
	private Supplierproductline supplierproductline;

	public Supplierorderline() {
	}

	public Supplierorderline(SupplierorderlineId id) {
		this.id = id;
	}

	public Supplierorderline(SupplierorderlineId id,
			Supplierorder supplierorder, Supplierproductline supplierproductline) {
		this.id = id;
		this.supplierorder = supplierorder;
		this.supplierproductline = supplierproductline;
	}

	public SupplierorderlineId getId() {
		return this.id;
	}

	public void setId(SupplierorderlineId id) {
		this.id = id;
	}

	public Supplierorder getSupplierorder() {
		return this.supplierorder;
	}

	public void setSupplierorder(Supplierorder supplierorder) {
		this.supplierorder = supplierorder;
	}

	public Supplierproductline getSupplierproductline() {
		return this.supplierproductline;
	}

	public void setSupplierproductline(Supplierproductline supplierproductline) {
		this.supplierproductline = supplierproductline;
	}

}
