package Hibernate.model;

// Generated 2015�~6��23�� �U��07:41:21 by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String userName;
	private Integer userPhone;
	private String userType;
	private String userRemark;
	private String userStatus;

	public User() {
	}

	public User(int userId, String userType, String userStatus) {
		this.userId = userId;
		this.userType = userType;
		this.userStatus = userStatus;
	}

	public User(int userId, String userName, Integer userPhone,
			String userType, String userRemark, String userStatus) {
		this.userId = userId;
		this.userName = userName;
		this.userPhone = userPhone;
		this.userType = userType;
		this.userRemark = userRemark;
		this.userStatus = userStatus;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(Integer userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getUserRemark() {
		return this.userRemark;
	}

	public void setUserRemark(String userRemark) {
		this.userRemark = userRemark;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

}
