package com.pccw.srm.batch.dto;

import java.io.Serializable;
import java.util.Date;

public class SPCBANewCSLRptDto implements Serializable, BatchLoaderDto {
	private static final long serialVersionUID = 4114022796313545744L;
	
	public final String[] columnNames = {
			"SHOP_ID",
			"CHANNEL",
			"BRAND",
			"SALES_CREATE_DATE",
			"SUBMITTED_DATE",
			"SALES_TYPE",
			"MOBILE_NO",
			"AF_SERIAL_NO",
			"REGISTERED_NAME",
			"GENDER",
			"REGISTERED_ID_TYPE",
			"CONTACT_TEL",
			"EMAIL_ADDRESS",
			"DATE_OF_BIRTH",
			"ACCOUNT_TYPE",
			"HK_RESIDENT_FLAG",
			"MODEL_OF_MOBILE_EQUIPMENT",
			"IMEI",
			"SIM_CARD_NO",
			"MOBILE_REMARK",
			"RATE_PLAN_ID",
			"RATE_PLAN_CODE",
			"RATE_PLAN_DESC",
			"MONTHLY_CHARGE",
			"BILL_CYCLE",
			"RATE_PLAN_REMARK",
			"RATE_PLAN_ENTITLEMENT_ENG",
			"RATE_PLAN_ENTITLEMENT_CHI",
			"RATE_PLAN_SYS_ENTITLEMENT",
			"RATE_PLAN_OPTION_CODE",
			"PROGRAM_NAME_ENG",
			"PROGRAM_NAME_CHI",
			"PROGRAM_ID",
			"PROJECT_CODE",
			"PROGRAM_START_DATE",
			"PROGRAM_END_DATE",
			"PROGRAM_REMOVAL_DATE",
			"COMMENCEMENT_DATE",
			"EXPIRY_DATE",
			"PROGRAM_ENTITLEMENT_ENG",
			"PROGRAM_ENTITLEMENT_CHI",
			"PROGRAM_CODE",
			"PROGRAM_FIELD1_LABEL",
			"PROGRAM_FIELD1_VALUE",
			"PROGRAM_FIELD2_LABEL",
			"PROGRAM_FIELD2_VALUE",
			"PROGRAM_FIELD3_LABEL",
			"PROGRAM_FIELD3_VALUE",
			"PROGRAM_FIELD4_LABEL",
			"PROGRAM_FIELD4_VALUE",
			"PROGRAM_FIELD5_LABEL",
			"PROGRAM_FIELD5_VALUE",
			"IDD_ROAMING_SUBSCRIPTION",
			"VAS_SUBSCRIPTIONS",
			"VAS_DESC",
			"VAS_ID",
			"VAS_CODE",
			"VAS_ENTITLEMENT_ENG",
			"VAS_ENTITLEMENT_CHI",
			"VAS_CHARGE",
			"FORM_STATUS",
			"RNO",
			"DONOR_NETWORK_OPERATOR",
			"CUT_OVER_DATE",
			"CUT_OVER_TIME",
			"SERVICE_EFFECTIVE_DATE",
			"COMMON_PROGRAM_NAME",
			"COMMON_PROGRAM_ID",
			"COMMON_PROGRAM_ENTITLEMENT_ENG",
			"COMMON_PROGRAM_CODE",
			"COMMON_PROGRAM_LABELS",
			"CREATOR_ID",
			"CREATOR_DEALER",
			"CREATE_SUB_DEALER",
			"UPDATER_ID",
			"UPDATER_NAME",
			"UPDATER_DEALER",
			"UPDATER_SUB_DEALER",
			"WPOS_SUBMITTED_BY",
			"WPOS_SUBMITTED_DATE",
			"PREPAYMENT_WAIVER"
	};
	
	private String SHOP_ID;
	private String CHANNEL;
	private String BRAND;
	private Date SALES_CREATE_DATE;
	private Date SUBMITTED_DATE;
	private String SALES_TYPE;
	private String MOBILE_NO;
	private String AF_SERIAL_NO;
	private String REGISTERED_NAME;
	private String GENDER;
	private String REGISTERED_ID_TYPE;
	private String CONTACT_TEL;
	private String EMAIL_ADDRESS;
	private String DATE_OF_BIRTH;
	private String ACCOUNT_TYPE;
	private String HK_RESIDENT_FLAG;
	private String MODEL_OF_MOBILE_EQUIPMENT;
	private String IMEI;
	private String SIM_CARD_NO;
	private String MOBILE_REMARK;
	private String RATE_PLAN_ID;
	private String RATE_PLAN_CODE;
	private String RATE_PLAN_DESC;
	private Double MONTHLY_CHARGE;
	private String BILL_CYCLE;
	private String RATE_PLAN_REMARK;
	private String RATE_PLAN_ENTITLEMENT_ENG;
	private String RATE_PLAN_ENTITLEMENT_CHI;
	private String RATE_PLAN_SYS_ENTITLEMENT;
	private String RATE_PLAN_OPTION_CODE;
	private String PROGRAM_NAME_ENG;
	private String PROGRAM_NAME_CHI;
	private String PROGRAM_ID;
	private String PROJECT_CODE;
	private Date PROGRAM_START_DATE;
	private Date PROGRAM_END_DATE;
	private Date PROGRAM_REMOVAL_DATE;
	private Date COMMENCEMENT_DATE;
	private Date EXPIRY_DATE;
	private String PROGRAM_ENTITLEMENT_ENG;
	private String PROGRAM_ENTITLEMENT_CHI;
	private String PROGRAM_CODE;
	private String PROGRAM_FIELD1_LABEL;
	private String PROGRAM_FIELD1_VALUE;
	private String PROGRAM_FIELD2_LABEL;
	private String PROGRAM_FIELD2_VALUE;
	private String PROGRAM_FIELD3_LABEL;
	private String PROGRAM_FIELD3_VALUE;
	private String PROGRAM_FIELD4_LABEL;
	private String PROGRAM_FIELD4_VALUE;
	private String PROGRAM_FIELD5_LABEL;
	private String PROGRAM_FIELD5_VALUE;
	private Double IDD_ROAMING_SUBSCRIPTION;
	private String VAS_SUBSCRIPTIONS;
	private String VAS_DESC;
	private String VAS_ID;
	private String VAS_CODE;
	private String VAS_ENTITLEMENT_ENG;
	private String VAS_ENTITLEMENT_CHI;
	private Double VAS_CHARGE;
	private String FORM_STATUS;
	private String RNO;
	private String DONOR_NETWORK_OPERATOR;
	private Date CUT_OVER_DATE;
	private String CUT_OVER_TIME;
	private Date SERVICE_EFFECTIVE_DATE;
	private String COMMON_PROGRAM_NAME;
	private String COMMON_PROGRAM_ID;
	private String COMMON_PROGRAM_ENTITLEMENT_ENG;
	private String COMMON_PROGRAM_CODE;
	private String COMMON_PROGRAM_LABELS;
	private String CREATOR_ID;
	private String CREATOR_DEALER;
	private String CREATE_SUB_DEALER;
	private String UPDATER_ID;
	private String UPDATER_NAME;
	private String UPDATER_DEALER;
	private String UPDATER_SUB_DEALER;
	private String WPOS_SUBMITTED_BY;
	private Date WPOS_SUBMITTED_DATE;
	private String PREPAYMENT_WAIVER;

	public SPCBANewCSLRptDto() {

	}

	public SPCBANewCSLRptDto(String sHOP_ID, String cHANNEL, String bRAND, Date sALES_CREATE_DATE, Date sUBMITTED_DATE,
			String sALES_TYPE, String mOBILE_NO, String aF_SERIAL_NO, String rEGISTERED_NAME, String gENDER,
			String rEGISTERED_ID_TYPE, String cONTACT_TEL, String eMAIL_ADDRESS, String dATE_OF_BIRTH,
			String aCCOUNT_TYPE, String hK_RESIDENT_FLAG, String mODEL_OF_MOBILE_EQUIPMENT, String iMEI,
			String sIM_CARD_NO, String mOBILE_REMARK, String rATE_PLAN_ID, String rATE_PLAN_CODE, String rATE_PLAN_DESC,
			Double mONTHLY_CHARGE, String bILL_CYCLE, String rATE_PLAN_REMARK, String rATE_PLAN_ENTITLEMENT_ENG,
			String rATE_PLAN_ENTITLEMENT_CHI, String rATE_PLAN_SYS_ENTITLEMENT, String rATE_PLAN_OPTION_CODE,
			String pROGRAM_NAME_ENG, String pROGRAM_NAME_CHI, String pROGRAM_ID, String pROJECT_CODE,
			Date pROGRAM_START_DATE, Date pROGRAM_END_DATE, Date pROGRAM_REMOVAL_DATE, Date cOMMENCEMENT_DATE,
			Date eXPIRY_DATE, String pROGRAM_ENTITLEMENT_ENG, String pROGRAM_ENTITLEMENT_CHI, String pROGRAM_CODE,
			String pROGRAM_FIELD1_LABEL, String pROGRAM_FIELD1_VALUE, String pROGRAM_FIELD2_LABEL,
			String pROGRAM_FIELD2_VALUE, String pROGRAM_FIELD3_LABEL, String pROGRAM_FIELD3_VALUE,
			String pROGRAM_FIELD4_LABEL, String pROGRAM_FIELD4_VALUE, String pROGRAM_FIELD5_LABEL,
			String pROGRAM_FIELD5_VALUE, Double iDD_ROAMING_SUBSCRIPTION, String vAS_SUBSCRIPTIONS, String vAS_DESC,
			String vAS_ID, String vAS_CODE, String vAS_ENTITLEMENT_ENG, String vAS_ENTITLEMENT_CHI, Double vAS_CHARGE,
			String fORM_STATUS, String rNO, String dONOR_NETWORK_OPERATOR, Date cUT_OVER_DATE, String cUT_OVER_TIME,
			Date sERVICE_EFFECTIVE_DATE, String cOMMON_PROGRAM_NAME, String cOMMON_PROGRAM_ID,
			String cOMMON_PROGRAM_ENTITLEMENT_ENG, String cOMMON_PROGRAM_CODE, String cOMMON_PROGRAM_LABELS,
			String cREATOR_ID, String cREATOR_DEALER, String cREATE_SUB_DEALER, String uPDATER_ID, String uPDATER_NAME,
			String uPDATER_DEALER, String uPDATER_SUB_DEALER, String wPOS_SUBMITTED_BY, Date wPOS_SUBMITTED_DATE,
			String pREPAYMENT_WAIVER) {
		super();
		SHOP_ID = sHOP_ID;
		CHANNEL = cHANNEL;
		BRAND = bRAND;
		SALES_CREATE_DATE = sALES_CREATE_DATE;
		SUBMITTED_DATE = sUBMITTED_DATE;
		SALES_TYPE = sALES_TYPE;
		MOBILE_NO = mOBILE_NO;
		AF_SERIAL_NO = aF_SERIAL_NO;
		REGISTERED_NAME = rEGISTERED_NAME;
		GENDER = gENDER;
		REGISTERED_ID_TYPE = rEGISTERED_ID_TYPE;
		CONTACT_TEL = cONTACT_TEL;
		EMAIL_ADDRESS = eMAIL_ADDRESS;
		DATE_OF_BIRTH = dATE_OF_BIRTH;
		ACCOUNT_TYPE = aCCOUNT_TYPE;
		HK_RESIDENT_FLAG = hK_RESIDENT_FLAG;
		MODEL_OF_MOBILE_EQUIPMENT = mODEL_OF_MOBILE_EQUIPMENT;
		IMEI = iMEI;
		SIM_CARD_NO = sIM_CARD_NO;
		MOBILE_REMARK = mOBILE_REMARK;
		RATE_PLAN_ID = rATE_PLAN_ID;
		RATE_PLAN_CODE = rATE_PLAN_CODE;
		RATE_PLAN_DESC = rATE_PLAN_DESC;
		MONTHLY_CHARGE = mONTHLY_CHARGE;
		BILL_CYCLE = bILL_CYCLE;
		RATE_PLAN_REMARK = rATE_PLAN_REMARK;
		RATE_PLAN_ENTITLEMENT_ENG = rATE_PLAN_ENTITLEMENT_ENG;
		RATE_PLAN_ENTITLEMENT_CHI = rATE_PLAN_ENTITLEMENT_CHI;
		RATE_PLAN_SYS_ENTITLEMENT = rATE_PLAN_SYS_ENTITLEMENT;
		RATE_PLAN_OPTION_CODE = rATE_PLAN_OPTION_CODE;
		PROGRAM_NAME_ENG = pROGRAM_NAME_ENG;
		PROGRAM_NAME_CHI = pROGRAM_NAME_CHI;
		PROGRAM_ID = pROGRAM_ID;
		PROJECT_CODE = pROJECT_CODE;
		PROGRAM_START_DATE = pROGRAM_START_DATE;
		PROGRAM_END_DATE = pROGRAM_END_DATE;
		PROGRAM_REMOVAL_DATE = pROGRAM_REMOVAL_DATE;
		COMMENCEMENT_DATE = cOMMENCEMENT_DATE;
		EXPIRY_DATE = eXPIRY_DATE;
		PROGRAM_ENTITLEMENT_ENG = pROGRAM_ENTITLEMENT_ENG;
		PROGRAM_ENTITLEMENT_CHI = pROGRAM_ENTITLEMENT_CHI;
		PROGRAM_CODE = pROGRAM_CODE;
		PROGRAM_FIELD1_LABEL = pROGRAM_FIELD1_LABEL;
		PROGRAM_FIELD1_VALUE = pROGRAM_FIELD1_VALUE;
		PROGRAM_FIELD2_LABEL = pROGRAM_FIELD2_LABEL;
		PROGRAM_FIELD2_VALUE = pROGRAM_FIELD2_VALUE;
		PROGRAM_FIELD3_LABEL = pROGRAM_FIELD3_LABEL;
		PROGRAM_FIELD3_VALUE = pROGRAM_FIELD3_VALUE;
		PROGRAM_FIELD4_LABEL = pROGRAM_FIELD4_LABEL;
		PROGRAM_FIELD4_VALUE = pROGRAM_FIELD4_VALUE;
		PROGRAM_FIELD5_LABEL = pROGRAM_FIELD5_LABEL;
		PROGRAM_FIELD5_VALUE = pROGRAM_FIELD5_VALUE;
		IDD_ROAMING_SUBSCRIPTION = iDD_ROAMING_SUBSCRIPTION;
		VAS_SUBSCRIPTIONS = vAS_SUBSCRIPTIONS;
		VAS_DESC = vAS_DESC;
		VAS_ID = vAS_ID;
		VAS_CODE = vAS_CODE;
		VAS_ENTITLEMENT_ENG = vAS_ENTITLEMENT_ENG;
		VAS_ENTITLEMENT_CHI = vAS_ENTITLEMENT_CHI;
		VAS_CHARGE = vAS_CHARGE;
		FORM_STATUS = fORM_STATUS;
		RNO = rNO;
		DONOR_NETWORK_OPERATOR = dONOR_NETWORK_OPERATOR;
		CUT_OVER_DATE = cUT_OVER_DATE;
		CUT_OVER_TIME = cUT_OVER_TIME;
		SERVICE_EFFECTIVE_DATE = sERVICE_EFFECTIVE_DATE;
		COMMON_PROGRAM_NAME = cOMMON_PROGRAM_NAME;
		COMMON_PROGRAM_ID = cOMMON_PROGRAM_ID;
		COMMON_PROGRAM_ENTITLEMENT_ENG = cOMMON_PROGRAM_ENTITLEMENT_ENG;
		COMMON_PROGRAM_CODE = cOMMON_PROGRAM_CODE;
		COMMON_PROGRAM_LABELS = cOMMON_PROGRAM_LABELS;
		CREATOR_ID = cREATOR_ID;
		CREATOR_DEALER = cREATOR_DEALER;
		CREATE_SUB_DEALER = cREATE_SUB_DEALER;
		UPDATER_ID = uPDATER_ID;
		UPDATER_NAME = uPDATER_NAME;
		UPDATER_DEALER = uPDATER_DEALER;
		UPDATER_SUB_DEALER = uPDATER_SUB_DEALER;
		WPOS_SUBMITTED_BY = wPOS_SUBMITTED_BY;
		WPOS_SUBMITTED_DATE = wPOS_SUBMITTED_DATE;
		PREPAYMENT_WAIVER = pREPAYMENT_WAIVER;
	}

	@Override
	public String[] getColumnNames() {
		return columnNames;
	}

	public String getSHOP_ID() {
		return SHOP_ID;
	}

	public void setSHOP_ID(String sHOP_ID) {
		SHOP_ID = sHOP_ID;
	}

	public String getCHANNEL() {
		return CHANNEL;
	}

	public void setCHANNEL(String cHANNEL) {
		CHANNEL = cHANNEL;
	}

	public String getBRAND() {
		return BRAND;
	}

	public void setBRAND(String bRAND) {
		BRAND = bRAND;
	}

	public Date getSALES_CREATE_DATE() {
		return SALES_CREATE_DATE;
	}

	public void setSALES_CREATE_DATE(Date sALES_CREATE_DATE) {
		SALES_CREATE_DATE = sALES_CREATE_DATE;
	}

	public Date getSUBMITTED_DATE() {
		return SUBMITTED_DATE;
	}

	public void setSUBMITTED_DATE(Date sUBMITTED_DATE) {
		SUBMITTED_DATE = sUBMITTED_DATE;
	}

	public String getSALES_TYPE() {
		return SALES_TYPE;
	}

	public void setSALES_TYPE(String sALES_TYPE) {
		SALES_TYPE = sALES_TYPE;
	}

	public String getMOBILE_NO() {
		return MOBILE_NO;
	}

	public void setMOBILE_NO(String mOBILE_NO) {
		MOBILE_NO = mOBILE_NO;
	}

	public String getAF_SERIAL_NO() {
		return AF_SERIAL_NO;
	}

	public void setAF_SERIAL_NO(String aF_SERIAL_NO) {
		AF_SERIAL_NO = aF_SERIAL_NO;
	}

	public String getREGISTERED_NAME() {
		return REGISTERED_NAME;
	}

	public void setREGISTERED_NAME(String rEGISTERED_NAME) {
		REGISTERED_NAME = rEGISTERED_NAME;
	}

	public String getGENDER() {
		return GENDER;
	}

	public void setGENDER(String gENDER) {
		GENDER = gENDER;
	}

	public String getREGISTERED_ID_TYPE() {
		return REGISTERED_ID_TYPE;
	}

	public void setREGISTERED_ID_TYPE(String rEGISTERED_ID_TYPE) {
		REGISTERED_ID_TYPE = rEGISTERED_ID_TYPE;
	}

	public String getCONTACT_TEL() {
		return CONTACT_TEL;
	}

	public void setCONTACT_TEL(String cONTACT_TEL) {
		CONTACT_TEL = cONTACT_TEL;
	}

	public String getEMAIL_ADDRESS() {
		return EMAIL_ADDRESS;
	}

	public void setEMAIL_ADDRESS(String eMAIL_ADDRESS) {
		EMAIL_ADDRESS = eMAIL_ADDRESS;
	}

	public String getDATE_OF_BIRTH() {
		return DATE_OF_BIRTH;
	}

	public void setDATE_OF_BIRTH(String dATE_OF_BIRTH) {
		DATE_OF_BIRTH = dATE_OF_BIRTH;
	}

	public String getACCOUNT_TYPE() {
		return ACCOUNT_TYPE;
	}

	public void setACCOUNT_TYPE(String aCCOUNT_TYPE) {
		ACCOUNT_TYPE = aCCOUNT_TYPE;
	}

	public String getHK_RESIDENT_FLAG() {
		return HK_RESIDENT_FLAG;
	}

	public void setHK_RESIDENT_FLAG(String hK_RESIDENT_FLAG) {
		HK_RESIDENT_FLAG = hK_RESIDENT_FLAG;
	}

	public String getMODEL_OF_MOBILE_EQUIPMENT() {
		return MODEL_OF_MOBILE_EQUIPMENT;
	}

	public void setMODEL_OF_MOBILE_EQUIPMENT(String mODEL_OF_MOBILE_EQUIPMENT) {
		MODEL_OF_MOBILE_EQUIPMENT = mODEL_OF_MOBILE_EQUIPMENT;
	}

	public String getIMEI() {
		return IMEI;
	}

	public void setIMEI(String iMEI) {
		IMEI = iMEI;
	}

	public String getSIM_CARD_NO() {
		return SIM_CARD_NO;
	}

	public void setSIM_CARD_NO(String sIM_CARD_NO) {
		SIM_CARD_NO = sIM_CARD_NO;
	}

	public String getMOBILE_REMARK() {
		return MOBILE_REMARK;
	}

	public void setMOBILE_REMARK(String mOBILE_REMARK) {
		MOBILE_REMARK = mOBILE_REMARK;
	}

	public String getRATE_PLAN_ID() {
		return RATE_PLAN_ID;
	}

	public void setRATE_PLAN_ID(String rATE_PLAN_ID) {
		RATE_PLAN_ID = rATE_PLAN_ID;
	}

	public String getRATE_PLAN_CODE() {
		return RATE_PLAN_CODE;
	}

	public void setRATE_PLAN_CODE(String rATE_PLAN_CODE) {
		RATE_PLAN_CODE = rATE_PLAN_CODE;
	}

	public String getRATE_PLAN_DESC() {
		return RATE_PLAN_DESC;
	}

	public void setRATE_PLAN_DESC(String rATE_PLAN_DESC) {
		RATE_PLAN_DESC = rATE_PLAN_DESC;
	}

	public Double getMONTHLY_CHARGE() {
		return MONTHLY_CHARGE;
	}

	public void setMONTHLY_CHARGE(Double mONTHLY_CHARGE) {
		MONTHLY_CHARGE = mONTHLY_CHARGE;
	}

	public String getBILL_CYCLE() {
		return BILL_CYCLE;
	}

	public void setBILL_CYCLE(String bILL_CYCLE) {
		BILL_CYCLE = bILL_CYCLE;
	}

	public String getRATE_PLAN_REMARK() {
		return RATE_PLAN_REMARK;
	}

	public void setRATE_PLAN_REMARK(String rATE_PLAN_REMARK) {
		RATE_PLAN_REMARK = rATE_PLAN_REMARK;
	}

	public String getRATE_PLAN_ENTITLEMENT_ENG() {
		return RATE_PLAN_ENTITLEMENT_ENG;
	}

	public void setRATE_PLAN_ENTITLEMENT_ENG(String rATE_PLAN_ENTITLEMENT_ENG) {
		RATE_PLAN_ENTITLEMENT_ENG = rATE_PLAN_ENTITLEMENT_ENG;
	}

	public String getRATE_PLAN_ENTITLEMENT_CHI() {
		return RATE_PLAN_ENTITLEMENT_CHI;
	}

	public void setRATE_PLAN_ENTITLEMENT_CHI(String rATE_PLAN_ENTITLEMENT_CHI) {
		RATE_PLAN_ENTITLEMENT_CHI = rATE_PLAN_ENTITLEMENT_CHI;
	}

	public String getRATE_PLAN_SYS_ENTITLEMENT() {
		return RATE_PLAN_SYS_ENTITLEMENT;
	}

	public void setRATE_PLAN_SYS_ENTITLEMENT(String rATE_PLAN_SYS_ENTITLEMENT) {
		RATE_PLAN_SYS_ENTITLEMENT = rATE_PLAN_SYS_ENTITLEMENT;
	}

	public String getRATE_PLAN_OPTION_CODE() {
		return RATE_PLAN_OPTION_CODE;
	}

	public void setRATE_PLAN_OPTION_CODE(String rATE_PLAN_OPTION_CODE) {
		RATE_PLAN_OPTION_CODE = rATE_PLAN_OPTION_CODE;
	}

	public String getPROGRAM_NAME_ENG() {
		return PROGRAM_NAME_ENG;
	}

	public void setPROGRAM_NAME_ENG(String pROGRAM_NAME_ENG) {
		PROGRAM_NAME_ENG = pROGRAM_NAME_ENG;
	}

	public String getPROGRAM_NAME_CHI() {
		return PROGRAM_NAME_CHI;
	}

	public void setPROGRAM_NAME_CHI(String pROGRAM_NAME_CHI) {
		PROGRAM_NAME_CHI = pROGRAM_NAME_CHI;
	}

	public String getPROGRAM_ID() {
		return PROGRAM_ID;
	}

	public void setPROGRAM_ID(String pROGRAM_ID) {
		PROGRAM_ID = pROGRAM_ID;
	}

	public String getPROJECT_CODE() {
		return PROJECT_CODE;
	}

	public void setPROJECT_CODE(String pROJECT_CODE) {
		PROJECT_CODE = pROJECT_CODE;
	}

	public Date getPROGRAM_START_DATE() {
		return PROGRAM_START_DATE;
	}

	public void setPROGRAM_START_DATE(Date pROGRAM_START_DATE) {
		PROGRAM_START_DATE = pROGRAM_START_DATE;
	}

	public Date getPROGRAM_END_DATE() {
		return PROGRAM_END_DATE;
	}

	public void setPROGRAM_END_DATE(Date pROGRAM_END_DATE) {
		PROGRAM_END_DATE = pROGRAM_END_DATE;
	}

	public Date getPROGRAM_REMOVAL_DATE() {
		return PROGRAM_REMOVAL_DATE;
	}

	public void setPROGRAM_REMOVAL_DATE(Date pROGRAM_REMOVAL_DATE) {
		PROGRAM_REMOVAL_DATE = pROGRAM_REMOVAL_DATE;
	}

	public Date getCOMMENCEMENT_DATE() {
		return COMMENCEMENT_DATE;
	}

	public void setCOMMENCEMENT_DATE(Date cOMMENCEMENT_DATE) {
		COMMENCEMENT_DATE = cOMMENCEMENT_DATE;
	}

	public Date getEXPIRY_DATE() {
		return EXPIRY_DATE;
	}

	public void setEXPIRY_DATE(Date eXPIRY_DATE) {
		EXPIRY_DATE = eXPIRY_DATE;
	}

	public String getPROGRAM_ENTITLEMENT_ENG() {
		return PROGRAM_ENTITLEMENT_ENG;
	}

	public void setPROGRAM_ENTITLEMENT_ENG(String pROGRAM_ENTITLEMENT_ENG) {
		PROGRAM_ENTITLEMENT_ENG = pROGRAM_ENTITLEMENT_ENG;
	}

	public String getPROGRAM_ENTITLEMENT_CHI() {
		return PROGRAM_ENTITLEMENT_CHI;
	}

	public void setPROGRAM_ENTITLEMENT_CHI(String pROGRAM_ENTITLEMENT_CHI) {
		PROGRAM_ENTITLEMENT_CHI = pROGRAM_ENTITLEMENT_CHI;
	}

	public String getPROGRAM_CODE() {
		return PROGRAM_CODE;
	}

	public void setPROGRAM_CODE(String pROGRAM_CODE) {
		PROGRAM_CODE = pROGRAM_CODE;
	}

	public String getPROGRAM_FIELD1_LABEL() {
		return PROGRAM_FIELD1_LABEL;
	}

	public void setPROGRAM_FIELD1_LABEL(String pROGRAM_FIELD1_LABEL) {
		PROGRAM_FIELD1_LABEL = pROGRAM_FIELD1_LABEL;
	}

	public String getPROGRAM_FIELD1_VALUE() {
		return PROGRAM_FIELD1_VALUE;
	}

	public void setPROGRAM_FIELD1_VALUE(String pROGRAM_FIELD1_VALUE) {
		PROGRAM_FIELD1_VALUE = pROGRAM_FIELD1_VALUE;
	}

	public String getPROGRAM_FIELD2_LABEL() {
		return PROGRAM_FIELD2_LABEL;
	}

	public void setPROGRAM_FIELD2_LABEL(String pROGRAM_FIELD2_LABEL) {
		PROGRAM_FIELD2_LABEL = pROGRAM_FIELD2_LABEL;
	}

	public String getPROGRAM_FIELD2_VALUE() {
		return PROGRAM_FIELD2_VALUE;
	}

	public void setPROGRAM_FIELD2_VALUE(String pROGRAM_FIELD2_VALUE) {
		PROGRAM_FIELD2_VALUE = pROGRAM_FIELD2_VALUE;
	}

	public String getPROGRAM_FIELD3_LABEL() {
		return PROGRAM_FIELD3_LABEL;
	}

	public void setPROGRAM_FIELD3_LABEL(String pROGRAM_FIELD3_LABEL) {
		PROGRAM_FIELD3_LABEL = pROGRAM_FIELD3_LABEL;
	}

	public String getPROGRAM_FIELD3_VALUE() {
		return PROGRAM_FIELD3_VALUE;
	}

	public void setPROGRAM_FIELD3_VALUE(String pROGRAM_FIELD3_VALUE) {
		PROGRAM_FIELD3_VALUE = pROGRAM_FIELD3_VALUE;
	}

	public String getPROGRAM_FIELD4_LABEL() {
		return PROGRAM_FIELD4_LABEL;
	}

	public void setPROGRAM_FIELD4_LABEL(String pROGRAM_FIELD4_LABEL) {
		PROGRAM_FIELD4_LABEL = pROGRAM_FIELD4_LABEL;
	}

	public String getPROGRAM_FIELD4_VALUE() {
		return PROGRAM_FIELD4_VALUE;
	}

	public void setPROGRAM_FIELD4_VALUE(String pROGRAM_FIELD4_VALUE) {
		PROGRAM_FIELD4_VALUE = pROGRAM_FIELD4_VALUE;
	}

	public String getPROGRAM_FIELD5_LABEL() {
		return PROGRAM_FIELD5_LABEL;
	}

	public void setPROGRAM_FIELD5_LABEL(String pROGRAM_FIELD5_LABEL) {
		PROGRAM_FIELD5_LABEL = pROGRAM_FIELD5_LABEL;
	}

	public String getPROGRAM_FIELD5_VALUE() {
		return PROGRAM_FIELD5_VALUE;
	}

	public void setPROGRAM_FIELD5_VALUE(String pROGRAM_FIELD5_VALUE) {
		PROGRAM_FIELD5_VALUE = pROGRAM_FIELD5_VALUE;
	}

	public Double getIDD_ROAMING_SUBSCRIPTION() {
		return IDD_ROAMING_SUBSCRIPTION;
	}

	public void setIDD_ROAMING_SUBSCRIPTION(Double iDD_ROAMING_SUBSCRIPTION) {
		IDD_ROAMING_SUBSCRIPTION = iDD_ROAMING_SUBSCRIPTION;
	}

	public String getVAS_SUBSCRIPTIONS() {
		return VAS_SUBSCRIPTIONS;
	}

	public void setVAS_SUBSCRIPTIONS(String vAS_SUBSCRIPTIONS) {
		VAS_SUBSCRIPTIONS = vAS_SUBSCRIPTIONS;
	}

	public String getVAS_DESC() {
		return VAS_DESC;
	}

	public void setVAS_DESC(String vAS_DESC) {
		VAS_DESC = vAS_DESC;
	}

	public String getVAS_ID() {
		return VAS_ID;
	}

	public void setVAS_ID(String vAS_ID) {
		VAS_ID = vAS_ID;
	}

	public String getVAS_CODE() {
		return VAS_CODE;
	}

	public void setVAS_CODE(String vAS_CODE) {
		VAS_CODE = vAS_CODE;
	}

	public String getVAS_ENTITLEMENT_ENG() {
		return VAS_ENTITLEMENT_ENG;
	}

	public void setVAS_ENTITLEMENT_ENG(String vAS_ENTITLEMENT_ENG) {
		VAS_ENTITLEMENT_ENG = vAS_ENTITLEMENT_ENG;
	}

	public String getVAS_ENTITLEMENT_CHI() {
		return VAS_ENTITLEMENT_CHI;
	}

	public void setVAS_ENTITLEMENT_CHI(String vAS_ENTITLEMENT_CHI) {
		VAS_ENTITLEMENT_CHI = vAS_ENTITLEMENT_CHI;
	}

	public Double getVAS_CHARGE() {
		return VAS_CHARGE;
	}

	public void setVAS_CHARGE(Double vAS_CHARGE) {
		VAS_CHARGE = vAS_CHARGE;
	}

	public String getFORM_STATUS() {
		return FORM_STATUS;
	}

	public void setFORM_STATUS(String fORM_STATUS) {
		FORM_STATUS = fORM_STATUS;
	}

	public String getRNO() {
		return RNO;
	}

	public void setRNO(String rNO) {
		RNO = rNO;
	}

	public String getDONOR_NETWORK_OPERATOR() {
		return DONOR_NETWORK_OPERATOR;
	}

	public void setDONOR_NETWORK_OPERATOR(String dONOR_NETWORK_OPERATOR) {
		DONOR_NETWORK_OPERATOR = dONOR_NETWORK_OPERATOR;
	}

	public Date getCUT_OVER_DATE() {
		return CUT_OVER_DATE;
	}

	public void setCUT_OVER_DATE(Date cUT_OVER_DATE) {
		CUT_OVER_DATE = cUT_OVER_DATE;
	}

	public String getCUT_OVER_TIME() {
		return CUT_OVER_TIME;
	}

	public void setCUT_OVER_TIME(String cUT_OVER_TIME) {
		CUT_OVER_TIME = cUT_OVER_TIME;
	}

	public Date getSERVICE_EFFECTIVE_DATE() {
		return SERVICE_EFFECTIVE_DATE;
	}

	public void setSERVICE_EFFECTIVE_DATE(Date sERVICE_EFFECTIVE_DATE) {
		SERVICE_EFFECTIVE_DATE = sERVICE_EFFECTIVE_DATE;
	}

	public String getCOMMON_PROGRAM_NAME() {
		return COMMON_PROGRAM_NAME;
	}

	public void setCOMMON_PROGRAM_NAME(String cOMMON_PROGRAM_NAME) {
		COMMON_PROGRAM_NAME = cOMMON_PROGRAM_NAME;
	}

	public String getCOMMON_PROGRAM_ID() {
		return COMMON_PROGRAM_ID;
	}

	public void setCOMMON_PROGRAM_ID(String cOMMON_PROGRAM_ID) {
		COMMON_PROGRAM_ID = cOMMON_PROGRAM_ID;
	}

	public String getCOMMON_PROGRAM_ENTITLEMENT_ENG() {
		return COMMON_PROGRAM_ENTITLEMENT_ENG;
	}

	public void setCOMMON_PROGRAM_ENTITLEMENT_ENG(String cOMMON_PROGRAM_ENTITLEMENT_ENG) {
		COMMON_PROGRAM_ENTITLEMENT_ENG = cOMMON_PROGRAM_ENTITLEMENT_ENG;
	}

	public String getCOMMON_PROGRAM_CODE() {
		return COMMON_PROGRAM_CODE;
	}

	public void setCOMMON_PROGRAM_CODE(String cOMMON_PROGRAM_CODE) {
		COMMON_PROGRAM_CODE = cOMMON_PROGRAM_CODE;
	}

	public String getCOMMON_PROGRAM_LABELS() {
		return COMMON_PROGRAM_LABELS;
	}

	public void setCOMMON_PROGRAM_LABELS(String cOMMON_PROGRAM_LABELS) {
		COMMON_PROGRAM_LABELS = cOMMON_PROGRAM_LABELS;
	}

	public String getCREATOR_ID() {
		return CREATOR_ID;
	}

	public void setCREATOR_ID(String cREATOR_ID) {
		CREATOR_ID = cREATOR_ID;
	}

	public String getCREATOR_DEALER() {
		return CREATOR_DEALER;
	}

	public void setCREATOR_DEALER(String cREATOR_DEALER) {
		CREATOR_DEALER = cREATOR_DEALER;
	}

	public String getCREATE_SUB_DEALER() {
		return CREATE_SUB_DEALER;
	}

	public void setCREATE_SUB_DEALER(String cREATE_SUB_DEALER) {
		CREATE_SUB_DEALER = cREATE_SUB_DEALER;
	}

	public String getUPDATER_ID() {
		return UPDATER_ID;
	}

	public void setUPDATER_ID(String uPDATER_ID) {
		UPDATER_ID = uPDATER_ID;
	}

	public String getUPDATER_NAME() {
		return UPDATER_NAME;
	}

	public void setUPDATER_NAME(String uPDATER_NAME) {
		UPDATER_NAME = uPDATER_NAME;
	}

	public String getUPDATER_DEALER() {
		return UPDATER_DEALER;
	}

	public void setUPDATER_DEALER(String uPDATER_DEALER) {
		UPDATER_DEALER = uPDATER_DEALER;
	}

	public String getUPDATER_SUB_DEALER() {
		return UPDATER_SUB_DEALER;
	}

	public void setUPDATER_SUB_DEALER(String uPDATER_SUB_DEALER) {
		UPDATER_SUB_DEALER = uPDATER_SUB_DEALER;
	}

	public String getWPOS_SUBMITTED_BY() {
		return WPOS_SUBMITTED_BY;
	}

	public void setWPOS_SUBMITTED_BY(String wPOS_SUBMITTED_BY) {
		WPOS_SUBMITTED_BY = wPOS_SUBMITTED_BY;
	}

	public Date getWPOS_SUBMITTED_DATE() {
		return WPOS_SUBMITTED_DATE;
	}

	public void setWPOS_SUBMITTED_DATE(Date wPOS_SUBMITTED_DATE) {
		WPOS_SUBMITTED_DATE = wPOS_SUBMITTED_DATE;
	}

	public String getPREPAYMENT_WAIVER() {
		return PREPAYMENT_WAIVER;
	}

	public void setPREPAYMENT_WAIVER(String pREPAYMENT_WAIVER) {
		PREPAYMENT_WAIVER = pREPAYMENT_WAIVER;
	}

	@Override
	public String toString() {
		return "SPCBANewCSLRptDto [SHOP_ID=" + SHOP_ID + ", CHANNEL=" + CHANNEL + ", BRAND=" + BRAND
				+ ", SALES_CREATE_DATE=" + SALES_CREATE_DATE + ", SUBMITTED_DATE=" + SUBMITTED_DATE + ", SALES_TYPE="
				+ SALES_TYPE + ", MOBILE_NO=" + MOBILE_NO + ", AF_SERIAL_NO=" + AF_SERIAL_NO + ", REGISTERED_NAME="
				+ REGISTERED_NAME + ", GENDER=" + GENDER + ", REGISTERED_ID_TYPE=" + REGISTERED_ID_TYPE
				+ ", CONTACT_TEL=" + CONTACT_TEL + ", EMAIL_ADDRESS=" + EMAIL_ADDRESS + ", DATE_OF_BIRTH="
				+ DATE_OF_BIRTH + ", ACCOUNT_TYPE=" + ACCOUNT_TYPE + ", HK_RESIDENT_FLAG=" + HK_RESIDENT_FLAG
				+ ", MODEL_OF_MOBILE_EQUIPMENT=" + MODEL_OF_MOBILE_EQUIPMENT + ", IMEI=" + IMEI + ", SIM_CARD_NO="
				+ SIM_CARD_NO + ", MOBILE_REMARK=" + MOBILE_REMARK + ", RATE_PLAN_ID=" + RATE_PLAN_ID
				+ ", RATE_PLAN_CODE=" + RATE_PLAN_CODE + ", RATE_PLAN_DESC=" + RATE_PLAN_DESC + ", MONTHLY_CHARGE="
				+ MONTHLY_CHARGE + ", BILL_CYCLE=" + BILL_CYCLE + ", RATE_PLAN_REMARK=" + RATE_PLAN_REMARK
				+ ", RATE_PLAN_ENTITLEMENT_ENG=" + RATE_PLAN_ENTITLEMENT_ENG + ", RATE_PLAN_ENTITLEMENT_CHI="
				+ RATE_PLAN_ENTITLEMENT_CHI + ", RATE_PLAN_SYS_ENTITLEMENT=" + RATE_PLAN_SYS_ENTITLEMENT
				+ ", RATE_PLAN_OPTION_CODE=" + RATE_PLAN_OPTION_CODE + ", PROGRAM_NAME_ENG=" + PROGRAM_NAME_ENG
				+ ", PROGRAM_NAME_CHI=" + PROGRAM_NAME_CHI + ", PROGRAM_ID=" + PROGRAM_ID + ", PROJECT_CODE="
				+ PROJECT_CODE + ", PROGRAM_START_DATE=" + PROGRAM_START_DATE + ", PROGRAM_END_DATE=" + PROGRAM_END_DATE
				+ ", PROGRAM_REMOVAL_DATE=" + PROGRAM_REMOVAL_DATE + ", COMMENCEMENT_DATE=" + COMMENCEMENT_DATE
				+ ", EXPIRY_DATE=" + EXPIRY_DATE + ", PROGRAM_ENTITLEMENT_ENG=" + PROGRAM_ENTITLEMENT_ENG
				+ ", PROGRAM_ENTITLEMENT_CHI=" + PROGRAM_ENTITLEMENT_CHI + ", PROGRAM_CODE=" + PROGRAM_CODE
				+ ", PROGRAM_FIELD1_LABEL=" + PROGRAM_FIELD1_LABEL + ", PROGRAM_FIELD1_VALUE=" + PROGRAM_FIELD1_VALUE
				+ ", PROGRAM_FIELD2_LABEL=" + PROGRAM_FIELD2_LABEL + ", PROGRAM_FIELD2_VALUE=" + PROGRAM_FIELD2_VALUE
				+ ", PROGRAM_FIELD3_LABEL=" + PROGRAM_FIELD3_LABEL + ", PROGRAM_FIELD3_VALUE=" + PROGRAM_FIELD3_VALUE
				+ ", PROGRAM_FIELD4_LABEL=" + PROGRAM_FIELD4_LABEL + ", PROGRAM_FIELD4_VALUE=" + PROGRAM_FIELD4_VALUE
				+ ", PROGRAM_FIELD5_LABEL=" + PROGRAM_FIELD5_LABEL + ", PROGRAM_FIELD5_VALUE=" + PROGRAM_FIELD5_VALUE
				+ ", IDD_ROAMING_SUBSCRIPTION=" + IDD_ROAMING_SUBSCRIPTION + ", VAS_SUBSCRIPTIONS=" + VAS_SUBSCRIPTIONS
				+ ", VAS_DESC=" + VAS_DESC + ", VAS_ID=" + VAS_ID + ", VAS_CODE=" + VAS_CODE + ", VAS_ENTITLEMENT_ENG="
				+ VAS_ENTITLEMENT_ENG + ", VAS_ENTITLEMENT_CHI=" + VAS_ENTITLEMENT_CHI + ", VAS_CHARGE=" + VAS_CHARGE
				+ ", FORM_STATUS=" + FORM_STATUS + ", RNO=" + RNO + ", DONOR_NETWORK_OPERATOR=" + DONOR_NETWORK_OPERATOR
				+ ", CUT_OVER_DATE=" + CUT_OVER_DATE + ", CUT_OVER_TIME=" + CUT_OVER_TIME + ", SERVICE_EFFECTIVE_DATE="
				+ SERVICE_EFFECTIVE_DATE + ", COMMON_PROGRAM_NAME=" + COMMON_PROGRAM_NAME + ", COMMON_PROGRAM_ID="
				+ COMMON_PROGRAM_ID + ", COMMON_PROGRAM_ENTITLEMENT_ENG=" + COMMON_PROGRAM_ENTITLEMENT_ENG
				+ ", COMMON_PROGRAM_CODE=" + COMMON_PROGRAM_CODE + ", COMMON_PROGRAM_LABELS=" + COMMON_PROGRAM_LABELS
				+ ", CREATOR_ID=" + CREATOR_ID + ", CREATOR_DEALER=" + CREATOR_DEALER + ", CREATE_SUB_DEALER="
				+ CREATE_SUB_DEALER + ", UPDATER_ID=" + UPDATER_ID + ", UPDATER_NAME=" + UPDATER_NAME
				+ ", UPDATER_DEALER=" + UPDATER_DEALER + ", UPDATER_SUB_DEALER=" + UPDATER_SUB_DEALER
				+ ", WPOS_SUBMITTED_BY=" + WPOS_SUBMITTED_BY + ", WPOS_SUBMITTED_DATE=" + WPOS_SUBMITTED_DATE
				+ ", PREPAYMENT_WAIVER=" + PREPAYMENT_WAIVER + "]";
	}
}
